### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by bipoza**

### CODE REVIEW

**Review by erral — CHANGES_REQUESTED** [review]
We need to change all places where volto-addon-template is present. For instance Makefile has some bits yet.

**Comment by erral** [comment]
> We need to change all places where volto-addon-template is present. For instance Makefile has some bits yet.

See: https://github.com/eea/volto-clms-utils/blob/master/Makefile#L4

**Review by erral — APPROVED** [review]

**Review by ionlizarazu — CHANGES_REQUESTED** [review]
README has volto-addon-template info

**Comment by bipoza** [comment]
> README has volto-addon-template info

This will not be updated automatically when we release it with the tpl variables?
https://github.com/eea/volto-clms-utils/blob/develop/README.md.tpl#L46

**Comment by erral** [comment]
I don't think Jenkins changes the README

**Comment by bipoza** [comment]
> I don't think Jenkins changes the README

I think it is ready. We can use the bootstrap function to change the necessary files through the templates. 
Once the command is executed, it will make the necessary changes and the templates will be removed.

```
yarn bootstrap
```

https://github.com/eea/volto-clms-utils/blob/develop/bootstrap#L13

**Review by ionlizarazu — APPROVED** [review]

**Pull request merged**
